### ISSUE TITLE
SelectPhotoAsync issue on Galaxy S4 (Android)

### ISSUE THREAD

**Issue by DavePilks** [jamesmontemagno/Xamarin.Plugins#128]
Hi

When I try to use the `SelectPhotoAsync` on the Galaxy S4, it works perfectly except that, after I select the image, it flashes the Splash Screen for a second before returning to the previous screen.

Any idea what could be causing this?

**Comment by jamesmontemagno** [comment]
Which version of android is it running? Can you create a http://gist.github.com with the full catlog?

**Comment by TunTunAg** [comment]
I also facing the problem as follow:

I used media picker (from the Xlabs) in my Xamarin app. Its working in Xiomi note, Nexus 6,LG and Mi3 W.
But when I test with Note2 and Note3. Its crash when tacking photo or select the photo from gallery.
I try to use the CrossMedia plugin. Still crash.
Pls, help me. Is there any other idea?

I added the permission on manifest as follow:

android.permission.CAMERA And android.permission.WRITE_EXTERNAL_STORAGE

**Comment by jamesmontemagno** [comment]
I will need crash log or logcat file to get more information.

**Comment by TunTunAg** [comment]
hi @jamesmontemagno 

error is as below : 

Android.Views.InflateException: Binary XML file line #37: Error inflating class <unknown> ---> System.Exception:  ---> 
System.Exception: Binary XML file line #35: Error inflating class <unknown> ---> System.Exception:  ---> 
System.Exception: Can't convert to color: type=0x2
  at --- End of managed exception stack trace ---
  at java.lang.UnsupportedOperationException: Can't convert to color: type=0x2
  at at android.content.res.TypedArray.getColor(TypedArray.java:327)
  at at android.widget.TextView.<init>(TextView.java:1003)
  at at android.widget.TextView.<init>(TextView.java:908)
  at at java.lang.reflect.Constructor.constructNative(Native Method)
  at at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  at at android.view.LayoutInflater.createView(LayoutInflater.java:600)
  at at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
  at at android.view.LayoutInflater.onCreateView(LayoutInflater.java:675)
  at at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:700)
  at at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
  at at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
  at at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
  at at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
  at at com.android.internal.widget.ActionBarView.initTitle(ActionBarView.java:1200)
  at at com.android.internal.widget.ActionBarView.setDisplayOptions(ActionBarView.java:982)
  at at com.android.internal.widget.ActionBarView.<init>(ActionBarView.java:398)
  at at java.lang.reflect.Constructor.constructNative(Native Method)
  at at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  at at android.view.LayoutInflater.createView(LayoutInflater.java:600)
  at at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702)
  at at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
  at at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
  at at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
  at at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
  at at android.view.LayoutInflater.inflate(LayoutInflater.java:354)
  at at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:3296)
  at at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:3359)
  at at com.android.internal.policy.impl.PhoneWindow.getDecorView(PhoneWindow.java:1886)
  at at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3131)
  at at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
  at at android.app.ActivityThread.access$900(ActivityThread.java:175)
  at at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
  at at android.os.Handler.dispatchMessage(Handler.java:102)
  at at android.os.Looper.loop(Looper.java:146)
  at at android.app.ActivityThread.main(ActivityThread.java:5602)
  at at java.lang.reflect.Method.invokeNative(Native Method)
  at at java.lang.reflect.Method.invoke(Method.java:515)
  at at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
  at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
  at at dalvik.system.NativeStart.main(Native Method)
  --- End of inner exception stack trace ---

**Comment by TunTunAg** [comment]
hi @jamesmontemagno 

Problem solved.   android:theme="@android:style/Theme.Material"  is not support in Note2 and 3. 
I  changed to android:theme="@android:style/Theme.Holo".  Now working.

Thanks.

**Comment by jamesmontemagno** [comment]
You should take a look into AppCompat: https://blog.xamarin.com/android-tips-hello-material-design-v7-appcompat/
