### ISSUE TITLE
Exception on getting CrossConnectivity.Current

### ISSUE THREAD

**Issue by heartquake** [jamesmontemagno/Xamarin.Plugins#168]
Updated XF (2.0.0.6490) and Connectivity Plugin (2.0.1) to the latest versions. I just have a single line in the constructor of WP8 project that uses the plugin and it is:
if (CrossConnectivity.Current.IsConnected)

That's all but I am getting the following exception. It was working on older XF and CP.

Please somebody help. I just feel really tired. I hated using plugins for Xamarin.Forms but sometimes I just don't have a choice.

Note: I'm not getting any errors on Droid and iOS

{System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NotImplementedException: The method or operation is not implemented.
at Windows.Networking.Connectivity.ConnectionProfile.GetNetworkConnectivityLevel()
at Plugin.Connectivity.ConnectivityImplementation.get_IsConnected()
at Plugin.Connectivity.ConnectivityImplementation..ctor()
at Plugin.Connectivity.CrossConnectivity.CreateConnectivity()
at Plugin.Connectivity.CrossConnectivity.<>c.<.cctor>b__7_0()
at System.Lazy

1.CreateValue()
   at System.Lazy
1.LazyInitValue()
at System.Lazy`1.get_Value()
at Plugin.Connectivity.CrossConnectivity.get_Current()
at AppName.App..ctor()
at AppName.WP8.MainPage..ctor()
--- End of inner exception stack trace ---
at System.Windows.Navigation.PageResourceContentLoader.EndLoad(IAsyncResult asyncResult)
at System.Windows.Navigation.NavigationService.ContentLoader_BeginLoad_Callback(IAsyncResult result)}

**Comment by jamesmontemagno** [comment]
Was fixed in 2.0.2

**Comment by SabrinaAbid** [comment]
still not fixed

**Comment by jamesmontemagno** [comment]
This was fixed here in 202: https://github.com/jamesmontemagno/Xamarin.Plugins/commit/153b91bcb0653cd2bb89e79715b9b7bf57f9d178 


Specifically this code:
https://github.com/jamesmontemagno/ConnectivityPlugin/blob/master/src/Connectivity.Plugin.WindowsPhone8/ConnectivityImplementation.cs#L63-L87

If you are still having an issue it may be different so please open an issue at: https://github.com/jamesmontemagno/ConnectivityPlugin
