### ISSUE TITLE
[Media] Windows Phone RT 8.1 - Bug in the TakePhotoAsync() method

### ISSUE THREAD

**Issue by avorobjovs** [jamesmontemagno/Xamarin.Plugins#321]
Please take a moment to fill out the following (change to preview to check or place x in []) and remove all unused areas

This is a 
- [x] Bug
- [] Feature Request

Which plugin does this impact:
- [] Battery
- [] Connectivity
- [] Contacts
- [] DeviceInfo
- [] ExternalMaps
- [] Geolocator
- [x] Media
- [] Permissions
- [] Settings
- [] Text To Speech
- [] Vibrate
- Other:

## Bug

Version Number of Plugin: 2.3.0
Device Tested On: Nokia Lumia 830, Windows Phone 8.1 Update 2, OS version 8.10.15148.160
Simulator Tested On:

### Expected Behavior

The TakePhotoAsync() method returns MediaFile object.

### Actual Behavior

The TakePhotoAsync() method raises an exception.

### Steps to reproduce the Behavior

1. Create new Windows Phone RT 8.1 application. 
2. Add a button to the MainPage.xaml
3. Add an event handler method for the button to the MainPage.xaml.cs code-behaviour file,
4. In the event handler method call the CrossMedia.Current.Initialize() method, then call the CrossMedia.Current.TakePhotoAsync() method.
5. The "Windows.UI.Xaml.Markup.XamlParseException: XAML parsing failed." exception is thrown.

=======================

Full exception stack trace:

Windows.UI.Xaml.Markup.XamlParseException: XAML parsing failed.
at Windows.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
at DMX.Helper.CameraCaptureUI.InitializeComponent()
at DMX.Helper.CameraCaptureUI..ctor()
at Plugin.Media.MediaImplementation.d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
at Media.WP.MainPage.d__11.MoveNext()

========================

There is a small test project in the attachment to check and reproduce this bug.

[Media.WP.zip](https://github.com/jamesmontemagno/Xamarin.Plugins/files/297744/Media.WP.zip)

**Comment by avorobjovs** [comment]
Full exception stack trace:
`
CrossMedia.Current.TakePhotoAsync exception: Windows.UI.Xaml.Markup.XamlParseException: XAML parsing failed.
   at Windows.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
   at DMX.Helper.CameraCaptureUI.InitializeComponent()
   at DMX.Helper.CameraCaptureUI..ctor()
   at Plugin.Media.MediaImplementation.<TakePhotoAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Media.WP.MainPage.<TakePhoto_Click>d__11.MoveNext()
`

**Comment by avorobjovs** [comment]
There is a small test project in the attachment 
[Media.WP.zip](https://github.com/jamesmontemagno/Xamarin.Plugins/files/297715/Media.WP.zip)
to check and reproduce this bug.

**Comment by abhimanyusinghal** [comment]
We are also getting same exception in our project

**Comment by Thowk** [comment]
Same problem here. The problem is caused by project configuration. Xaml files are missing in output library.
At least, some workaround exist:
http://forums.xamarin.com/discussion/comment/201503/#Comment_201503

**Comment by jamesmontemagno** [comment]
This issue was moved to jamesmontemagno/MediaPlugin#5
