### ISSUE TITLE
InvocationTargetException when try to use.

### ISSUE THREAD

**Issue by ilfat** [jamesmontemagno/Xamarin.Plugins#70]
Steps to reproduce:
Install library over nuget in xamarin studo or vs to PCL 7 profile library or android project. Try to use settings in code. In this place get{ return CrossSettings.Current;} you will get exception:
```
    Java.Lang.RuntimeException: java.lang.reflect.InvocationTargetException
  at --- End of managed exception stack trace ---
  at java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
  at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
  at Caused by: java.lang.reflect.InvocationTargetException
  at at java.lang.reflect.Method.invoke(Native Method)
  at at java.lang.reflect.Method.invoke(Method.java:372)
  at at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
  at ... 1 more
  at Caused by: md52ce486a14f4bcd95899665e9d932190b.JavaProxyThrowable: System.NotImplementedException: This functionality is not implemented in the portable version of this assembly.  You should reference the Xam.Plugins.Settings NuGet package from your main application project in order to reference the platform-specific implementation.
  at at Refractored.Xam.Settings.CrossSettings.get_Current () <IL 0x00013, 0x000b8>
  at at PlusofonXamarin.Core.Settings.get_AppSettings () <IL 0x00001, 0x0004f>
  at at PlusofonXamarin.Core.Settings.get_PhoneNumber () <IL 0x00001, 0x0004f>
  at at ru.plusofonxamarin.Internet.Server..ctor () <IL 0x00009, 0x0008b>
  at ru.plusofonxamarin.Launch.LaunchActivity.OnCreate (Android.OS.Bundle) [0x00015] in c:\mobile-app-xamarin\plusofon-xamarin\launch\LaunchActivity.cs:26
  at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (intptr,intptr,intptr) [0x00011] in /Users/builder/data/lanes/1780/3518c4ce/source/monodroid/src/Mono.Android/platforms/android-21/src/generated/Android.App.Activity.cs:2707
  at at (wrapper dynamic-method) object.2ce906d6-f9d4-475e-afee-5355d4f24809 (intptr,intptr,intptr) <IL 0x00017, 0x00053>
  at at md519c93d3e2f8fd6ffce50be888407e8c6.LaunchActivity.n_onCreate(Native Method)
  at at md519c93d3e2f8fd6ffce50be888407e8c6.LaunchActivity.onCreate(LaunchActivity.java:29)
  at at android.app.Activity.performCreate(Activity.java:5976)
  at at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
  at at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2262)
  at at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2369)
  at at android.app.ActivityThread.access$800(ActivityThread.java:149)
  at at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1289)
  at at android.os.Handler.dispatchMessage(Handler.java:102)
  at at android.os.Looper.loop(Looper.java:135)
  at at android.app.ActivityThread.main(ActivityThread.java:5258)
  at ... 4 more
```

**Comment by ilfat** [comment]
Sorry, it was my oversight. Just can give advice - write more complete tutorial. Thank you for you work!
