### ISSUE TITLE
IllegalArgumentException when returning to app

### ISSUE THREAD

**Issue by michaelnero** [jamesmontemagno/Xamarin.Plugins#92]
I'm hoping you can help me resolve an issue I'm having with the Media plugin on Android. I keep getting an IllegalArgumentException when trying to take/choose a photo, and then returning to my app. Am I missing something?  Here's the relevant log output:

[WindowManager] 
[WindowManager] android.view.WindowLeaked: Activity md59ee9cf477177d0ff9c7b0779e1ebfcbe.MediaPickerActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{26ebb2fa V.E..... R......D 0,0-264,369} that was originally added here
[WindowManager] 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:363)
[WindowManager] 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:271)
[WindowManager] 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
[WindowManager] 	at android.app.Dialog.show(Dialog.java:298)
[WindowManager] 	at md5282f1122c1313907b9bf274dd2c2f344.FormsApplicationActivity.n_onRestart(Native Method)
[WindowManager] 	at md5282f1122c1313907b9bf274dd2c2f344.FormsApplicationActivity.onRestart(FormsApplicationActivity.java:78)
[WindowManager] 	at android.app.Instrumentation.callActivityOnRestart(Instrumentation.java:1246)
[WindowManager] 	at android.app.Activity.performRestart(Activity.java:6057)
[WindowManager] 	at android.app.Activity.performResume(Activity.java:6068)
[WindowManager] 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2975)
[WindowManager] 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3017)
[WindowManager] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
[WindowManager] 	at android.os.Handler.dispatchMessage(Handler.java:102)
[WindowManager] 	at android.os.Looper.loop(Looper.java:135)
[WindowManager] 	at android.app.ActivityThread.main(ActivityThread.java:5254)
[WindowManager] 	at java.lang.reflect.Method.invoke(Native Method)
[WindowManager] 	at java.lang.reflect.Method.invoke(Method.java:372)
[WindowManager] 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
[WindowManager] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
[art] Explicit concurrent mark sweep GC freed 15177(1351KB) AllocSpace objects, 22(17MB) LOS objects, 39% free, 8MB/14MB, paused 824us total 47.398ms
[Mono] GC_OLD_BRIDGE num-objects 75 num_hash_entries 124 sccs size 122 init 0.00ms df1 1.98ms sort 0.12ms dfs2 1.19ms setup-cb 1.10ms free-data 0.46ms links 64/64/90/4 dfs passes 263/186
[Mono] GC_MINOR: (Nursery full) pause 18.65ms, total 19.14ms, bridge 54.51ms promoted 144K major 4592K los 8411K
[Mono] DllImport attempting to load: '/system/lib/liblog.so'.
[Mono] DllImport loaded library '/system/lib/liblog.so'.
[Mono] DllImport searching in: '/system/lib/liblog.so' ('/system/lib/liblog.so').
[Mono] Searching for '__android_log_print'.
[Mono] Probing '__android_log_print'.
[Mono] Found as '__android_log_print'.
[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] Java.Lang.IllegalArgumentException: Exception of type 'Java.Lang.IllegalArgumentException' was thrown.
[MonoDroid] at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /Users/builder/data/lanes/1978/f98871a9/source/mono/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:61
[MonoDroid] at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>m__0 (object) [0x00000] in /Users/builder/data/lanes/1978/f98871a9/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1006
[MonoDroid] at Android.App.SyncContext/<Post>c__AnonStorey0.<>m__0 () [0x00000] in /Users/builder/data/lanes/1978/f98871a9/source/monodroid/src/Mono.Android/src/Android.App/SyncContext.cs:18
[MonoDroid] at Java.Lang.Thread/RunnableImplementor.Run () [0x0000b] in /Users/builder/data/lanes/1978/f98871a9/source/monodroid/src/Mono.Android/src/Java.Lang/Thread.cs:36
[MonoDroid] at Java.Lang.IRunnableInvoker.n_Run (intptr,intptr) [0x00009] in /Users/builder/data/lanes/1978/f98871a9/source/monodroid/src/Mono.Android/platforms/android-21/src/generated/Java.Lang.IRunnable.cs:71
[MonoDroid] at (wrapper dynamic-method) object.ff277ee1-98ab-4217-9a83-0e944563edd3 (intptr,intptr) <IL 0x00011, 0x0003b>
[MonoDroid]   --- End of managed exception stack trace ---
[MonoDroid] java.lang.IllegalArgumentException: View=com.android.internal.policy.impl.PhoneWindow$DecorView{26ebb2fa G.E..... R.....ID 0,0-264,369} not attached to window manager
[MonoDroid] 	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:396)
[MonoDroid] 	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:322)
[MonoDroid] 	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:116)
[MonoDroid] 	at android.app.Dialog.dismissDialog(Dialog.java:341)
[MonoDroid] 	at android.app.Dialog.dismiss(Dialog.java:324)
[MonoDroid] 	at mono.java.lang.RunnableImplementor.n_run(Native Method)
[MonoDroid] 	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:29)
[MonoDroid] 	at android.os.Handler.handleCallback(Handler.java:739)
[MonoDroid] 	at android.os.Handler.dispatchMessage(Handler.java:95)
[MonoDroid] 	at android.os.Looper.loop(Looper.java:135)
[MonoDroid] 	at android.app.ActivityThread.main(ActivityThread.java:5254)
[MonoDroid] 	at java.lang.reflect.Method.invoke(Native Method)
[MonoDroid] 	at java.lang.reflect.Method.invoke(Method.java:372)
[MonoDroid] 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
[MonoDroid] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
[AndroidRuntime] Shutting down VM
[AndroidRuntime] FATAL EXCEPTION: main
[AndroidRuntime] Process: com.work_ify.mobileapp, PID: 26461
[AndroidRuntime] java.lang.IllegalArgumentException: View=com.android.internal.policy.impl.PhoneWindow$DecorView{26ebb2fa G.E..... R.....ID 0,0-264,369} not attached to window manager
[AndroidRuntime] 	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:396)
[AndroidRuntime] 	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:322)
[AndroidRuntime] 	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:116)
[AndroidRuntime] 	at android.app.Dialog.dismissDialog(Dialog.java:341)
[AndroidRuntime] 	at android.app.Dialog.dismiss(Dialog.java:324)
[AndroidRuntime] 	at mono.java.lang.RunnableImplementor.n_run(Native Method)
[AndroidRuntime] 	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:29)
[AndroidRuntime] 	at android.os.Handler.handleCallback(Handler.java:739)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:95)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:135)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:5254)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Method.java:372)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by michaelnero** [comment]
Sorry about that and never mind. This was because I was attempting to open a dialog when returning to the app. Closing the issue.
